# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766fc09071be8540179c581bd4b990e4af25405bf98e2a7886166314657dcdbfe88e88159d0cb4ee20e7173d7b1e9c5ca47f6a8da6fcdfb7dd463256869c71fb

test:
  secret_key_base: 88b126794217e3d0a25e5f97fa9f757f4b2089467fcf95a9a7335db51134fabb6679c1a48418a059efd9188dd001dfc4190d1b7578dba5d07eca68bd129b018d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
